### ISSUE TITLE
soft_purge fails with - ArgumentError - wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by mrthan** [fastly/fastly-rails#61]
Ruby ruby 2.3.1p112 (2016-04-26 revision 54768) [i686-linux]
Rails 4.2.7

All my soft purges are failing with a multi-argument error:
```
ArgumentError - wrong number of arguments (given 2, expected 1):
  fastly-rails (0.7.0) lib/fastly-rails/client.rb:11:in `purge_by_key'
  fastly-rails (0.7.0) lib/fastly-rails.rb:26:in `purge_by_key'
  fastly-rails (0.7.0) lib/fastly-rails/active_record/surrogate_key.rb:41:in `soft_purge'
```

I'm calling FastlyRails myself in some cases, and in others using the suggest approach:

```ruby
class License < ActiveRecord::Base
    attr_accessor :state_action

    # == soft purge - invalidates without deleting
    after_update :soft_purge
    after_destroy :soft_purge
end
```

I'm suspecting it's possibly an change/issue with ruby 2.3 and the use of the `DelegateClass` in **fastly-rails/client.rb**

As far as I can tell, the rails-fastly surrogate_key wrapper for ActiveRecords seems to never defer to the fastly/client.rb to carry out purges (which handles soft=true)

```
 # Purge the specified path from your cache.
  def purge(url, soft=false)
    client.purge(url, soft ? { headers: { 'Fastly-Soft-Purge' => "1"} } : {})
  end
```

It seems to do it all itself with a POST from `purge_by_key`

```ruby
module FastlyRails
  # A simple wrapper around the fastly-ruby client.
  class Client < DelegateClass(Fastly)
    def initialize(opts={})
      super(Fastly.new(opts))
    end

    def purge_by_key(key)
      client.require_key!
      client.post purge_url(key)
    end

    def purge_url(key)
      "/service/#{FastlyRails.service_id}/purge/#{URI.escape(key)}"
    end
  end
end
```

**Comment by mrthan** [comment]
oops.. forgot to check closed issues first.. https://github.com/fastly/fastly-rails/issues/57
